export const columns = [
  {
    uid: "id",
    name: "ID",
    sortable: true,
  },
  {
    uid: "nombre",
    name: "Nombre",
    sortable: true,
  },
  {
    uid: "genero",
    name: "Género",
    sortable: true,
  },
  {
    uid: "edad",
    name: "Edad",
    sortable: true,
  },
  {
    uid: "carrere",
    name: "Carrera",
    sortable: true,
  },
  { uid: "actions", name: "Acciones", sortable: false },
];

const users = [
  // {
  //   id: 1,
  //   name: "Tony Reichert",
  //   role: "CEO",
  //   team: "Management",
  //   age: "29",
  //   email: "tony.reichert@example.com",
  // },
  // {
  //   id: 2,
  //   name: "Zoey Lang",
  //   role: "Tech Lead",
  //   team: "Development",
  //   age: "25",
  //   email: "zoey.lang@example.com",
  // },
  // {
  //   id: 3,
  //   name: "Jane Fisher",
  //   role: "Sr. Dev",
  //   team: "Development",
  //   age: "22",
  //   email: "jane.fisher@example.com",
  // },
  // {
  //   id: 4,
  //   name: "William Howard",
  //   role: "C.M.",
  //   team: "Marketing",
  //   age: "28",
  //   email: "william.howard@example.com",
  // },
  // {
  //   id: 5,
  //   name: "Kristen Copper",
  //   role: "S. Manager",
  //   team: "Sales",
  //   age: "24",
  //   email: "kristen.cooper@example.com",
  // },
  // {
  //   id: 6,
  //   name: "Brian Kim",
  //   role: "P. Manager",
  //   team: "Management",
  //   age: "29",
  //   email: "brian.kim@example.com",
  // },
  // {
  //   id: 7,
  //   name: "Michael Hunt",
  //   role: "Designer",
  //   team: "Design",
  //   age: "27",
  //   email: "michael.hunt@example.com",
  // },
  // {
  //   id: 8,
  //   name: "Samantha Brooks",
  //   role: "HR Manager",
  //   team: "HR",
  //   age: "31",
  //   email: "samantha.brooks@example.com",
  // },
  // {
  //   id: 9,
  //   name: "Frank Harrison",
  //   role: "F. Manager",
  //   team: "Finance",
  //   age: "33",
  //   email: "frank.harrison@example.com",
  // },
  // {
  //   id: 10,
  //   name: "Emma Adams",
  //   role: "Ops Manager",
  //   team: "Operations",
  //   age: "35",
  //   email: "emma.adams@example.com",
  // },
  // {
  //   id: 11,
  //   name: "Brandon Stevens",
  //   role: "Jr. Dev",
  //   team: "Development",
  //   age: "22",
  //   email: "brandon.stevens@example.com",
  // },
  // {
  //   id: 12,
  //   name: "Megan Richards",
  //   role: "P. Manager",
  //   team: "Product",
  //   age: "28",
  //   email: "megan.richards@example.com",
  // },
  // {
  //   id: 13,
  //   name: "Oliver Scott",
  //   role: "S. Manager",
  //   team: "Security",
  //   age: "37",
  //   email: "oliver.scott@example.com",
  // },
  // {
  //   id: 14,
  //   name: "Grace Allen",
  //   role: "M. Specialist",
  //   team: "Marketing",
  //   age: "30",
  //   email: "grace.allen@example.com",
  // },
  // {
  //   id: 15,
  //   name: "Noah Carter",
  //   role: "IT Specialist",
  //   team: "I. Technology",
  //   age: "31",
  //   email: "noah.carter@example.com",
  // },
  // {
  //   id: 16,
  //   name: "Ava Perez",
  //   role: "Manager",
  //   team: "Sales",
  //   age: "29",
  //   email: "ava.perez@example.com",
  // },
  // {
  //   id: 17,
  //   name: "Liam Johnson",
  //   role: "Data Analyst",
  //   team: "Analysis",
  //   age: "28",
  //   email: "liam.johnson@example.com",
  // },
  // {
  //   id: 18,
  //   name: "Sophia Taylor",
  //   role: "QA Analyst",
  //   team: "Testing",
  //   age: "27",
  //   email: "sophia.taylor@example.com",
  // },
  // {
  //   id: 19,
  //   name: "Lucas Harris",
  //   role: "Administrator",
  //   team: "Information Technology",
  //   age: "32",
  //   email: "lucas.harris@example.com",
  // },
  // {
  //   id: 20,
  //   name: "Mia Robinson",
  //   role: "Coordinator",
  //   team: "Operations",
  //   age: "26",
  //   email: "mia.robinson@example.com",
  // },
];

export { users };
